name: Python Script Workflow

on:
  push:
    branches:
      - main  # Change this to your default branch
  schedule: # 2am CST
    - cron: '0 7 * * *'

jobs:
  run_script:
    runs-on: ubuntu-latest  # You can change the OS if needed

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Choose the desired Python version

    - name: Run Python Script
      run: |
        python get_new_data.py  # Replace with the actual script name and arguments

    - name: Commit and Push Changes
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git add .
        git commit -m "Update via GitHub Actions"
        git push